[project]
name = "airmise"
version = "3.1.0b0"
description = "The native experience of calling remote functions, like local ones."
authors = [{ name = "Likianta", email = "likianta@foxmail.com" }]
readme = "readme.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.13.3",
    "argsense>=1.1.2",
    "lk-utils>=3.8.0b5",
    "neoprint>=0.1.10a3",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling>=1.29.0"]

[dependency-groups]
dev = [
    "ipython>=9.16.0",
    "streamlit>=1.61.0",
    "streamlit-canary>=0.4.0a6",
]

[project.urls]
homepage = "https://github.com/likianta/airmise"

[tool.hatch.build.targets.wheel]
packages = ["airmise"]

[tool.ruff]
line-length = 80

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true

[tool.ruff.lint.isort]
force-single-line = true
relative-imports-order = "closest-to-furthest"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ty.rules]
# invalid-type-form = "ignore"
unresolved-attribute = "ignore"

[tool.uv]
prerelease = "allow"

[[tool.uv.index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

[[tool.uv.index]]
name = "likianta"
url = "http://localhost:2131/"
explicit = true

[tool.uv.sources]
# argsense = { index = "likianta" }
lk-utils = { index = "likianta" }
neoprint = { index = "likianta" }
streamlit-canary = { index = "likianta" }
